apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dnsendpoint.yaml
  - ./externalsecret.yaml
  - ./httproute.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/charts
    version: 84.1.0
    releaseName: kube-prometheus-stack
    namespace: observability
    includeCRDs: true
    valuesFile: ./values.yaml
patchesStrategicMerge:
  - ./remove-hook-annotations.yaml
