apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  scopes: '[groups, email]'
  policy.csv: |
    # Built-in role permissions
    p, role:admin, applications, *, */*, allow
    p, role:admin, applications, sync, */*, allow
    p, role:admin, applications, override, */*, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, applications, sync, */*, deny
    p, role:readonly, applications, override, */*, deny

    # Home-ops group bindings
    g, argocd-admins, role:admin
    g, argocd-maintainers, role:readonly
