# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paseo
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paseo-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: PASEO_PASSWORD
      remoteRef:
        key: paseo
        property: PASEO_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
