apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gateway.yaml
helmCharts:
  - name: ai-gateway-crds-helm
    repo: oci://docker.io/envoyproxy
    version: v0.6.0
    releaseName: aieg-crd
    namespace: network
    includeCRDs: true
  - name: ai-gateway-helm
    repo: oci://docker.io/envoyproxy
    version: v0.6.0
    releaseName: aieg
    namespace: network
    valuesFile: ./values.yaml
