apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
helmCharts:
  - name: external-dns
    repo: oci://ghcr.io/home-operations/charts-mirror
    version: 1.21.1
    releaseName: cloudflare-dns
    namespace: network
    includeCRDs: true
    valuesFile: ./values.yaml
