---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:

  reconcile:
    desc: Force Flux to pull in changes from your Git repository
    cmd: flux --namespace flux-system reconcile kustomization flux-system --with-source
    preconditions:
      - test -f {{.KUBECONFIG}}
      - which flux

  flux-local:
    desc: Run Flux Local Tests
    cmd: |
      flux-local test \
        --enable-helm \
        --all-namespaces \
        --path ./kubernetes/flux/cluster \
        -v
