apiVersion: v1
kind: Secret
metadata:
  name: authentik-values
  namespace: security
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:XlAG9e1rECHDBRa4kEbvaz2/Ahtk68ETGc8uSveshMAg2ff4ukCwNCa1XtZc396I5IX7Q7+ADSDte5/VbVyC7u+UmqBz1T2fM3PnSxjXPN65kv3QqyuodmitOJd+CIUHqwmN33/v1MV5w1dTR0Rb1nRm389KEfe0a1qxEX1uoqoxFcyBnyD95QfCW7CK3E65VPM7oR7fHn8KKRWw/6bg1qiJpfm/1ZGR9l0GGpkJjxloMxCs,iv:ZbCpzb0tsnIrtoxHMQZKvMtPr84YrrFBUFEDoPRib1o=,tag:E1vBr42Xb1iAWPNdlwaY5g==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbmJ6RjdlaWVxTWVYa2k4
        eTA3am9STWhpZ1R4RVNnUlVzZFo3Wm4rRWowClF6WXFkUkloN1ROVFVaRmkxSGVY
        QnRsdFA4dDhrTG5nQ1JJRHNwRGptTWcKLS0tIFB5UTVrOFQ3MGZWVythUVdlZFlq
        bmxDcnVjTVVRZWkzZ1hya0x0Q0RZYjAKdZWihdE4BRJQiygI6YCe1xOU0gBUPU5p
        ZlxoK6pMBFKauB1IRARE4ELBQHRDqNBpiGbjIAq9Dss5UIFRF+WWrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T06:02:09Z"
  mac: ENC[AES256_GCM,data:mGtl5h0b/25yMDpYNy27EFNvWvN58LUt5izbmy5L2vnZWZiJ0KsvEEWo7Dy2ix7PlUfPnEI+EvsKxux0rWa6Yqm+xisdJT9NlV9TP9jhXMU3aCzGdk/uYbAiGG7MnbAreeQRM5WOYr1jv0ztNY+9d89/TD24prGK9ROR7w1n/wY=,iv:pS+ykvVwKHVVMbd/5eSClEcZUzczpSzAXoP0dG6czOM=,tag:PACNDLW+lEv8Abl2HvXHpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
