apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  chartRef:
    kind: OCIRepository
    name: authentik
  interval: 1h
  values:
    postgresql:
      enabled: true
    redis:
      enabled: true
    authentik:
      secret_key: "${AUTHENTIK_SECRET_KEY}"
      error_reporting:
        enabled: false
    server:
      ingress:
        enabled: false
      route:
        main:
          enabled: true
          hostnames:
            - auth.${SECRET_DOMAIN}
          parentRefs:
            - name: envoy-external
              namespace: network
              sectionName: https
          matches:
            - path:
                type: PathPrefix
                value: /
