# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-admin-token
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: headlamp-admin-token
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          managed-by: external-secrets
          token-sync.home-ops.io/authoritative-source: k8s-secret
  dataFrom:
    - extract:
        key: headlamp-admin-token
