apiVersion: v1
kind: Secret
metadata:
  name: oauth-client-secret
  namespace: network
stringData:
  client-secret: ENC[AES256_GCM,data:6V0YY35p5LHbejY5LB44aS62UH3vD3eUBupDsBrVVp5Ph+AA0tWFU60+dTLBtRGEmrHRg8dmkSoCP44Syh+SIQ==,iv:k6f94WUVxqy6VixTM9JPMlPjOXoyHfWazE6cbYnvAbE=,tag:7XDCOYbIiRI/QC8I95Nefg==,type:str]
  google-client-secret: ENC[AES256_GCM,data:5JnSsvDA1Mmqn5djr726CzfEL103+GB3d0YgGIk=,iv:5XCEzy2gCs96abc8dU90/WyA0KfkwlFz1wQgwaEjl8A=,tag:UfLWcAJs58D/q6Itli/qJw==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtREplZWZKUDhrNGQycnNO
        cEY4SFZpMEt1ckNxOVYwTkdMdThwcjBBWjFVClFWaG4zMHNja1VsVE41dFBZbFVj
        TWFIOFVMWkZBekwyQ2t6Wk45V0Fya1EKLS0tIGpZV3BrVHlBbUZDVlo4UTQvMkhE
        NlFJZGsrajNhSkRiVy96Nk0wc3hBeG8KkydF+GgYI/2dKeYXyOAlmAlCo78UNZQu
        RWP7vOdYBWdIV+uC1zTcYBoD5erYdp9fBHuKG/OtJQtzwzXH4tgcog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T05:33:08Z"
  mac: ENC[AES256_GCM,data:4GV67cOICpl4apbjs8+UrsXVWwlE7ZeO5fx7VidKJN82XPWu50I/66HhJGrBbhDjshBsxsP/F/IKseFKyCWabkBbdR9oXFcryIsBRDmEiib1AnilXaDjk2tOd0LsdPUjt9W1t/J/6lAcLHL+kUw/JCAkNRYW0E+4RYfCwBX6/r0=,iv:iJSyOJ1zfzU+pg/AoN6PJ1MkSmQKANvae3+TGuync8s=,tag:SYWAq6k4lQ+CNtt/nTP/ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
