data: |
  apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: SecurityPolicy
  metadata:
    name: envoy-oauth-policy
    namespace: network
    annotations:
      home-ops.io/auth-mode: authentik
      home-ops.io/legacy-mode: available
  spec:
    targetRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: envoy-oauth
    oidc:
      provider:
        issuer: https://auth.${SECRET_DOMAIN}/application/o/home-ops
        authorizationEndpoint: https://auth.${SECRET_DOMAIN}/application/o/authorize/
      clientID: 706743218818-jp4s5vunfp9ac1euuu4j0sh5t46palg6.apps.googleusercontent.com
      clientSecret:
        name: oauth-client-secret
        namespace: network
      redirectURL: https://oauth.${SECRET_DOMAIN}/oauth2/callback
      logoutPath: /logout
      cookieDomain: ${SECRET_DOMAIN}
      cookieNames:
        accessToken: AccessToken
        idToken: IdToken
      scopes:
        - openid
        - email
        - profile
    jwt:
      providers:
        - name: authentik
          issuer: https://auth.${SECRET_DOMAIN}/application/o/home-ops
          remoteJWKS:
            uri: https://auth.${SECRET_DOMAIN}/application/o/home-ops/jwks/
          extractFrom:
            cookies:
              - IdToken
            headers:
              - name: Authorization
                valuePrefix: 'Bearer '
            params:
              - access_token
    authorization:
      defaultAction: Deny
      rules:
        - name: allow-authentik-groups
          action: Allow
          principal:
            jwt:
              provider: authentik
              claims:
                - name: groups
                  values:
                    - home-ops:protected
                - name: email_verified
                  values:
                    - "true"
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCLzlhYTc5emxRS0dzWCt4
        MXZJY2kySkhLNGxhR3R5bm5ZeUZiLzBpQWpFCnU4WXZ1bHlGaS80V1ZKNXNyNTN6
        enJXVm94d3pJQWYrTlIraWFPdUNOOFEKLS0tIEJ6NTFhWW9ORmQydmpEaTJhVyta
        VUJ4bXd2WEZ1WXBhUUpDdlJSdFQzL3cKP5IEv+VcpYrmfsJZNTJsza+MZbymzX3G
        LAAGG2kmYTXasgw+E7fL3+1DnG6l53fLllf90whgFVD7LTeXQG6ZBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-02T05:24:00Z"
  mac: ENC[AES256_GCM,data:ErbBAtJjv52afHX16zK27CC2DogealkVdQFhvIomnl8tk65QSOdnlLU7hCuNNuZaEVEHekKRBCl7AKSDo09nWa0c/qLqq3VmKPxPz/BWclJN6yUZZWVni5AjzE+75QSf77IYWL4lLCz7HemgW137lwAXmC8oEKcg9B7bosdqNYI=,iv:PI/S1ZQ5yTxdpvsdKQGSwduaLsgR2T7aeizMdZo1hsA=,tag:l1+izo6vr6G1UnjQK2YzBg==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.12.1
