apiVersion: v1
kind: Secret
metadata:
  name: oauth-client-secret
  namespace: network
  annotations:
    home-ops.io/auth-secret-mode: dual
stringData:
  authentik-client-secret: ENC[AES256_GCM,data:zD6L5IcmZxbpF75uUnCV3+FL65lxTBm2Ww/GzLWeeyza1mY=,iv:Obpe9Z0cbEWJrpS5sWtzIySrYglyxuxIgnsWaOqADtI=,tag:KAAKitmwnsD0i3DwP9g/VA==,type:str]
  legacy-google-client-secret: ENC[AES256_GCM,data:TiZc8W9k2ZahVMKJCg80Z72/2mmz6IoSLw78I80aWYuCHnk=,iv:PT7RzXliJfPlTtG7ay7GHvLQGcXy1qovHRgRc1mran4=,tag:R3OudtIvt8xr9sdlw7d9RQ==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTmN2VUZEb3pudFg4QkdG
        M0xBUkRTNkFWQTExek4zNVE5c1dnT2VWRkJBCmFEUFY4K0c3WmVuK0lrbVFwSWJR
        Sk5kRGxSZ3lvOGRZQ2ZiNWN1UCsrekEKLS0tIEw1MDBoTzkyVytVaDR0RTd6OXJJ
        ZitjcitRTnRUdDJUa01IL3ZQMVB3VWsKDybl9fbcimoIbWdvssHstRVCf5BI+Weq
        KDrkJvCGLtTNfciHjaP2r4NCxkPndFCiQIScfdY5U1njOQVM3/qc0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-02T04:00:08Z"
  mac: ENC[AES256_GCM,data:ikA+XYWknwbyRm9nbPXWZFnC7BMGMmfqCOFTOAv16pjjl419/KJ2cfxw16bJJ22M7SzP9IoonlGeDlZTNCJ+q16W5aVOnPpk6oGGOFpyZOL3CmtoDLpJFUuTXbx/0aOhaFVZ7EoddxmH2cBJmPYpXC6CbWvQ2TbZqT8b1+jvoIM=,iv:B1w1CU8uPsV06yOs9SGPbz/2mQXkVqD6+Wf9RSiTS/M=,tag:A34Xm2NErxpN24vdptjUqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
