apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-internal-policy
  namespace: network
  annotations:
    home-ops.io/auth-mode: authentik
    home-ops.io/legacy-mode: available
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:c4mOY5doc40aHvonuKysHzxvOZJqOAsMTQ==,iv:B+l0D88XAbYXB2HED7GS95+jvwqjlND34xHIRAEsvV8=,tag:8+lPi/57QOFsUDW9reQtuw==,type:str]
      kind: ENC[AES256_GCM,data:0fZxvp9WPA==,iv:iZcyc3RtqBugo37lFWY9Clmlgo9CS0oHWCPvlGfwBsA=,tag:LnuAwx2fNesyV8enSLVCXA==,type:str]
      name: ENC[AES256_GCM,data:ViLf+VIOyFtjc/7i0aa0hL24LB0=,iv:1YiA9tmoXdEKWOSx6Za+5VQfQsGwRHc6kZRnU1wOH0M=,tag:4Jfek0a7x5QH3aCEycpaAA==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:uBHhEEnPQCTioo8cMFAD/p/wfLKHSAXFfQNUmEB0MZF6jpd3PkFiE9XjuCRTipIp3+PJdg==,iv:tRIuwMzgjF2BoUBw6kVQFMzjsidsG6PlHY6/Bnk0/3w=,tag:BAj/GXPqoGKWbnNr+Kf46w==,type:str]
      authorizationEndpoint: ENC[AES256_GCM,data:3YK7+V5HJWR8Msobqc+G2u1CRTpHhiia44YJnmIp/GdipsNQWvBZEI9Ysq9akpq7nfEmqsyN,iv:epi6OdoNB0R9me2wpS6iMh2G8d6BTaIJNSSs3Ant5cc=,tag:epMU/RihaU11lg8sCS5bkg==,type:str]
    clientID: ENC[AES256_GCM,data:BCNOetnDhVyUoKJSQ5cEVTFdvnTqrN4A0BK+QHJtNas75oZsp/ubpSDGb/i0McJZAXP4kqD6vLvM8D7jluwZ/A4lSPFN6y0A,iv:CsXcGgfJWzfB9XfIiZsN/8Sv9Lvbz4IL3QfC76picc4=,tag:sGHZ05h4tcyJB56e5ODBEQ==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:5DdazIw0hapatAogrE05brX5vQ==,iv:Af5OpzvejMq8OAT3o8jmZJvUV68M5pRDHfsqyHL9Pxc=,tag:pHw0NymA3pLMRTqkcOTfHw==,type:str]
      namespace: ENC[AES256_GCM,data:PqDRAvYqRw==,iv:TufFNKMsQF4w5xKwLplCfLCjZOCLd8JiZcNvHMrnOgU=,tag:oSUD6IpVi4nrGEWmWuT40w==,type:str]
    redirectURL: ENC[AES256_GCM,data:K1MtMQkY6xpg83bKzYAd/Xt2vvlhBKLOs7CKHLPmM+7HpVbfhzp4k/lPFHTMSekfXLlIOCTLgg==,iv:wIFpB3KYXesR97DGS/4/wbjOmr+EdmOuEeGikwipe6A=,tag:j45pyEa5TYIG/2vTavW6Jg==,type:str]
    logoutPath: ENC[AES256_GCM,data:+LcoWbEwsg==,iv:eOnN8KmNvWTLAyRPHGFwIt4WBrWjIxgNpVq+w5R7qPA=,tag:dl2WK0jqwVkgLNwN3z2Tmw==,type:str]
    cookieDomain: ENC[AES256_GCM,data:4DZ0g1qTNgVg77ttYuM4+A==,iv:4P61vOyRvBwCOTJB8poP2KLLpz0nzW4fG6qsMWAoC0k=,tag:3lkCxvUONsEwcTYsOzGEOg==,type:str]
    cookieNames:
      accessToken: ENC[AES256_GCM,data:LEGGM3o3Sx7qL70=,iv:mbwtJd/Nk9JTTAWwN435M+A7GmT5pzC/8hp/IVUk0XA=,tag:wAyoKTDmvSnmm+RVBZ4pOA==,type:str]
      idToken: ENC[AES256_GCM,data:2EfMk5l/YQ==,iv:bEuS7Aji4E4IGAZs/NOxG8rt8g2L4+GVd41SeoaB35E=,tag:ElFI8shpS+htouqubYBtyA==,type:str]
    scopes:
      - ENC[AES256_GCM,data:YuCQy6ME,iv:YcwXs+WOrP649TLCZTW9UsrQ99fb+WVpdoQ7vsD2WF4=,tag:26LNK8x+HiMXHYn3+E2V/A==,type:str]
      - ENC[AES256_GCM,data:W3vqoAE=,iv:qSRpC7NnCAH5gnyegAS2YjeT1UA7Z00fwKDXQFQ3IMI=,tag:/9spon7Yc7Vpova5SbHgjg==,type:str]
      - ENC[AES256_GCM,data:GJ0yj2rW9Q==,iv:NPcVLcrjFAc16Ff2F7Lc/h0pLgSu4qkwz5tDcXj4xsQ=,tag:5Ag3oGho35gX9INa4BWgeA==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:4+ry7GWzYA7N,iv:5A8zg7slcegVfVEmi5siOe0lZg+Rgf2c9fANaL917Ts=,tag:0lsdblTomVe0s1nlBfUcLg==,type:str]
        issuer: ENC[AES256_GCM,data:6Jg6y6L53KdW53NujWq9jd6q1s3/sOBmDcoExIiB0b+iOloihR0EJe1uW5gqMJPmHTdHaA==,iv:KkTv9uSJ4MSskv3iJ9JHq21Dbd1oZnzSGxjlgWqb7Z4=,tag:Fp5QDC92DNJ+cTFcNqRgDQ==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:T6qZg5dD7Y3baxqXVrTammdez1/HuQCNzAnGRiUxyolcsn5QQKbe48WbrSrAPl4TsrOWGn1g0DsSUQ==,iv:i7i9WFfSR5D4f8RYeTiyJQnuVq6rrdHtmxPu2wAqVMY=,tag:lwnENWlviR+Aiqzj0cc2WA==,type:str]
        extractFrom:
          cookies:
            - ENC[AES256_GCM,data:s263K8ZPNg==,iv:FqOZs+HW2XCIU1QeQfhkCgSFQ+LQNymcS7uWSrXmuxA=,tag:Ze3VWrPvr5z1FCdg5GNGGQ==,type:str]
          headers:
            - name: ENC[AES256_GCM,data:+Qqj0fVAnkvocFAm2w==,iv:IF1gBf9A4Ogz/m/d0nmJ4STP+hw8WNkC2C6xa5fd08Q=,tag:xkqrChxyp24h7Yo0ChAQhQ==,type:str]
              valuePrefix: ENC[AES256_GCM,data:Rz2cyY40/w==,iv:3p5Paufi88IF+7vLP7ezTEN7uC2Jl0szYHFbD2444rE=,tag:MSCuyl3NGr+dLiDeigw0pg==,type:str]
          params:
            - ENC[AES256_GCM,data:pp9BllsTNPykXy7v,iv:zI1tL0fZWd95fmeGhyxD4fuH4ffnrrPqvRftt6loK14=,tag:yoOlWFy0MFrbJ2WtPDq6EQ==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:xI9DDA==,iv:cXgaKKh13Th4P7k1X4/iYDStkuaAfw+0+lPwD/Unsus=,tag:Otmi4hiDfvEPGRiCzys2Zg==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:YKZTP8nGqZF4wfv+yNArBBjMsx4IjQ==,iv:WbagIjG6XdEHKtYAQ3aGL0cIOvFJdoKguhAEDrPqgWA=,tag:iGMS6eY08rChP8o5vALw9A==,type:str]
        action: ENC[AES256_GCM,data:Yv6HvAo=,iv:nc6su3NQn6B84FfzPXYi/Jb4GsYm73uewe7JNG7Tktg=,tag:WOF3bp/A+//eK0l7Hl1GBg==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:8KTcK/8LAYJf,iv:QQskcv2kjAcczr/DNzQszrHSHchNUJe4PhqUXE5FG64=,tag:uuUJ/jPFr8199vTAi9ONUQ==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:XNksSeui,iv:361cCBjHqsbU4da4cphBai5jcpzp9B/fCMe+fS32ylY=,tag:rzekYlfLvMBT8xwrYnMLgA==,type:str]
                values:
                  - ENC[AES256_GCM,data:zcmWK9YzBtM/jhRFkPZWcA74,iv:7VdgwuAAFc5B3SczOxuATFB8LQ888q+WUiGOecoU/Vs=,tag:TnilgXRNs0bUq3v3QjHP5g==,type:str]
              - name: ENC[AES256_GCM,data:8m8s0RGGan+qZgSpdfo=,iv:qhubVkbpQidKQ4XA17R+DpidMWuI1Fejzc+mbIeTrJE=,tag:aCz5i3RhcRshhDuEnS/yUA==,type:str]
                values:
                  - ENC[AES256_GCM,data:Nx5+4w==,iv:rSW4CpXbX+YoIWQE2xbWxOntTVKTIVj6rIEWWD3claQ=,tag:cT6yMPqnEDuhYyEaPqkvjw==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcFFSdExaRkQ3dytIbjhF
        QlBuVWZXMnVtUStseFBpbXlvOFJvaUQzclRvCnN1eEkwenZHY0l6c2NEbTZvSU1T
        UWxyUGRSVzFUUEFRYkg5QVZhVGJqbTQKLS0tIEtKb0xONEs3MTBpY0ltMDV0TFZ0
        dk1penYyN3JBYjB4bUZxbUJ1UXBaZUEKTsBo/jfabklZCd2YLbh+R6awVUHX1pbf
        uq6kmPkU7+AH6VhZ2W5wHatnzFtgoo1Bv30moG69+Eb2yobk7YTsmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-02T05:24:57Z"
  mac: ENC[AES256_GCM,data:AkRWcyrCd0M0nhtikrkgDN3i+NjlYoOQmdLxxDLje+zkRpz6uBLZkEA6j5eUp2K+PHvun+hjiZRGnsIqamn20HzdyZCmgWcs6QkdXu9x2PNroBSSA8q/LZcxo3rTPIp/v92viX4mN39WCaXK31aWs7kTXmExUnruQ0ELVoQ1E1c=,iv:7QA6t/LeUqtH+/rpB7ZIXB8V18vdY8/pn6oFJ54NrYA=,tag:M2Mzgrb50waSqowEcq4QNw==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.12.1
