apiVersion: v1
kind: Secret
metadata:
  name: oauth-client-secret
  namespace: network
stringData:
  client-secret: ENC[AES256_GCM,data:DCs93JIHPCdUXND+KBmmlHtBQnygiUTLCeKG/r56+28=,iv:USITWLwEYYK0dQwWb+YdDY6SoVqBlln5X+UkpqlUXf0=,tag:MpSyn6bDvknkKQuwJhKRYQ==,type:str]
  google-client-secret: ENC[AES256_GCM,data:36t70YmlIgGP3l8yMHvvUc8gQB4ZN6Nl0v4oPKs=,iv:2+bAoUTtNtFYMqXgc8+HuYRyzB+FK6sTKJAjXeC54kU=,tag:5l6B1a8bXAMHqRaqLVzB0Q==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRjVBNjV5TEZLd2lvMm03
        WXNLMXlzUVVpWHRwUmtSS0tWV1I5cktaRnlrCnZrbE1TeWdRTklNTS9rQjBBRURC
        NVdCUmtwbkFuYW1hTmlyYzVYSkZtUUUKLS0tIFFDMWFsak5mTURQWndKYi9PbER0
        N1ZXSEVnbnhBMGNKMjNIU2NSQnNhNUkKngs+h6/G7I7OXRsu8hWxi9u9t9jLIXwu
        DtJnbqlnAw/qnihTuVSXD3QFyK2jXY1U6QgETRKDTMHEPbbMucw3aQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T04:09:35Z"
  mac: ENC[AES256_GCM,data:4kJKX1MDU1hanPFRMnh+9CSlm54HgLxnPbinffCF6t5RtlkNZvKpzrZVF0DGA2DDhLFnLGoc5ShyAlxofWP74eOW+V3K6u4/hFIGx9JhVpSgOhcnXLDIiBmbFdWiOJNkOF1+uwQZKfwSuweO/OtHxgUJFB3Zr/wtEq5hRIn0kWY=,iv:zHIpMdLontouMXMpPxEqM2LIkeYX4eYPTFUnAf97alc=,tag:RdyraUUBhINpxt6DPPwTBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
