apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-proxy
spec:
  jobLabel: envoy-proxy
  namespaceSelector:
    matchNames:
      - network
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
      honorLabels: true
      metricRelabelings:
        - action: keep
          sourceLabels: [__name__]
          regex: "envoy_http_.*|envoy_cluster_upstream_.*|envoy_ext_authz_.*|envoy_oauth_.*"
  selector:
    matchLabels:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/name: envoy
