# ExternalSecret Template Contract
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
#
# USAGE:
#   Place this file in your app's `app/` directory as `externalsecret.yaml`.
#   Reference it from your app's `app/kustomization.yaml`.
#
# PREREQUISITES:
#   - ClusterSecretStore "onepassword" is Ready (deployed by external-secrets/onepassword)
#   - A 1Password item exists in the "Kubernetes" vault with the matching item name
#
# FIELD MAPPING MODES (choose one):
#   Mode A — extract: pulls ALL custom fields from a single 1Password item into one Secret
#   Mode B — data:   pulls individual fields from one or more 1Password items into one Secret
#
# Replace ALL <placeholders> before committing.
#
# MODE A: extract all fields from a single 1Password item (most common)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: <app-name> # e.g., my-app
  namespace: <target-namespace> # e.g., default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 1h
  target:
    name: <app-name>-secret # name of the Kubernetes Secret to create
    creationPolicy: Owner # ESO owns the secret; deletes it when ExternalSecret is removed
  dataFrom:
    - extract:
        key: <1password-item-name> # item title in the 1Password "Kubernetes" vault (e.g., my-app)
---
# MODE B: map individual fields from one or more 1Password items
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: <app-name>
  namespace: <target-namespace>
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 1h
  target:
    name: <app-name>-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY # key in the resulting Kubernetes Secret
      remoteRef:
        key: <1password-item-name> # 1Password item title
        property: API_KEY # 1Password custom field name (SCREAMING_SNAKE_CASE)
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: <1password-item-name>
        property: DATABASE_PASSWORD
