# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: tailscale-config
spec:
  externalSecretName: tailscale-config
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: ["default"]
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: tailscale-config
      creationPolicy: Owner
      deletionPolicy: Retain
    data:
      - secretKey: TAILSCALE_DNS_SUFFIX
        remoteRef:
          key: tailscale
          property: TAILSCALE_DNS_SUFFIX
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
