apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./httproute.yaml
  - ./securitypolicy.yaml
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 4.6.2
    releaseName: oauth-pages
    namespace: default
    includeCRDs: true
    valuesFile: ./values.yaml
